# Generated by Django 5.1.5 on 2025-01-24 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('CODECLASSE', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('NOM_CLASSE', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('IDETUDIANT', models.AutoField(primary_key=True, serialize=False)),
                ('FILIERE', models.CharField(max_length=255)),
                ('EMAIL_ETUDIANT', models.EmailField(max_length=254)),
                ('PASSWORD', models.CharField(max_length=255)),
                ('NOM', models.CharField(max_length=255)),
                ('PRENOM', models.CharField(max_length=255)),
                ('DEPARTEMENT', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('IDPROFESSEUR', models.AutoField(primary_key=True, serialize=False)),
                ('DEPARTEMENT', models.CharField(max_length=255)),
                ('SPECIALITE', models.CharField(max_length=255)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PASSWORD', models.CharField(max_length=255)),
                ('NOM', models.CharField(max_length=255)),
                ('PRENOM', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('IDPROJECT', models.AutoField(primary_key=True, serialize=False)),
                ('DESCRIPTION', models.TextField()),
                ('DATE_DEBUT', models.DateField()),
                ('DATE_FIN', models.DateField()),
                ('NOM_PROJECT', models.CharField(max_length=255)),
                ('CODECLASSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('ID_GROUPE', models.AutoField(primary_key=True, serialize=False)),
                ('NOM_GROUPE', models.CharField(max_length=255)),
                ('NBR_MEMBRE', models.IntegerField()),
                ('IDPROJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.project')),
            ],
        ),
        migrations.CreateModel(
            name='Todoliste',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DESCRIPTIONTACHE', models.TextField()),
                ('STATUS', models.CharField(max_length=255)),
                ('DEADLINE', models.DateField()),
                ('IDETUDIANT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODECLASSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.classe')),
                ('IDETUDIANT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.etudiant')),
            ],
            options={
                'unique_together': {('IDETUDIANT', 'CODECLASSE')},
            },
        ),
        migrations.CreateModel(
            name='Construire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDETUDIANT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.etudiant')),
                ('ID_GROUPE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.groupe')),
            ],
            options={
                'unique_together': {('IDETUDIANT', 'ID_GROUPE')},
            },
        ),
        migrations.CreateModel(
            name='Creer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODECLASSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.classe')),
                ('IDPROFESSEUR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.professeur')),
            ],
            options={
                'unique_together': {('IDPROFESSEUR', 'CODECLASSE')},
            },
        ),
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDETUDIANT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.etudiant')),
                ('IDPROJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.project')),
            ],
            options={
                'unique_together': {('IDETUDIANT', 'IDPROJECT')},
            },
        ),
    ]
