# Generated by Django 5.1.5 on 2025-02-12 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_classe', models.CharField(max_length=255, unique=True)),
                ('nom_classe', models.CharField(max_length=255)),
                ('etudiants_nbr', models.PositiveIntegerField(default=0)),
                ('projets_nbr', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_groupe', models.CharField(max_length=255)),
                ('nbr_membre', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=255)),
                ('specialite', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('filiere', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=255)),
                ('classes', models.ManyToManyField(related_name='etudiants', to='base_de_donnee.classe')),
                ('groupes', models.ManyToManyField(related_name='membres', to='base_de_donnee.groupe')),
            ],
        ),
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evenement', models.CharField(max_length=255, null=True)),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField(null=True)),
                ('status', models.CharField(choices=[('rouge', 'rouge'), ('vert', 'vert'), ('bleu', 'bleu'), ('jaune', 'jaune')], max_length=10)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_time', to='base_de_donnee.etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='base_de_donnee.professeur'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nom_project', models.CharField(max_length=255)),
                ('code_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='base_de_donnee.classe')),
            ],
        ),
        migrations.AddField(
            model_name='groupe',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='base_de_donnee.project'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='projets',
            field=models.ManyToManyField(related_name='etudiants', to='base_de_donnee.project'),
        ),
        migrations.CreateModel(
            name='Taches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_tache', models.TextField()),
                ('status', models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé')], max_length=25)),
                ('deadline', models.DateField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='base_de_donnee.etudiant')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='base_de_donnee.groupe')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
            },
        ),
    ]
