# Generated by Django 5.1.5 on 2025-06-12 12:18

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_classe', models.CharField(max_length=255, unique=True)),
                ('nom_classe', models.CharField(max_length=255)),
                ('description', models.CharField(default='nouveau classe')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.CharField(max_length=255)),
                ('photo_profil', models.ImageField(default='images/profile.jpeg', upload_to='images/')),
                ('departement', models.CharField(max_length=255)),
                ('email_etudiant', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_groupe', models.CharField(max_length=255)),
                ('nbr_membre', models.PositiveIntegerField()),
                ('meet_link', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('livrable_requis', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateField(default=datetime.date.today)),
                ('end', models.DateField()),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(max_length=255, null=True)),
                ('photo_profil', models.ImageField(default='images/profile.jpeg', upload_to='images/')),
                ('specialite', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evenement', models.CharField(max_length=255, null=True)),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField(null=True)),
                ('status', models.CharField(choices=[('rouge', 'rouge'), ('vert', 'vert'), ('bleu', 'bleu'), ('jaune', 'jaune')], max_length=10)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_time', to='base_de_donnee.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='EtudiantClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.etudiant')),
            ],
            options={
                'unique_together': {('etudiant', 'classe')},
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='etudiants', through='base_de_donnee.EtudiantClasse', to='base_de_donnee.classe'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(max_length=50)),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='base_de_donnee.etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='groupes',
            field=models.ManyToManyField(blank=True, related_name='membres', to='base_de_donnee.groupe'),
        ),
        migrations.CreateModel(
            name='GroupeArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_groupe', models.CharField(max_length=255)),
                ('nbr_membre', models.PositiveIntegerField()),
                ('groupe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='base_de_donnee.groupe')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='groupesArchive',
            field=models.ManyToManyField(blank=True, related_name='membres', to='base_de_donnee.groupearchive'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='base_de_donnee.etudiant')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='base_de_donnee.groupe')),
                ('groupeArchive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_archive', to='base_de_donnee.groupearchive')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueTachesEtu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('taches_en_cours', models.IntegerField(default=0)),
                ('taches_terminees', models.IntegerField(default=0)),
                ('taches_en_retard', models.IntegerField(default=0)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_taches', to='base_de_donnee.etudiant')),
            ],
            options={
                'verbose_name': 'Historique des Tâches',
                'verbose_name_plural': 'Historiques des Tâches',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InstructionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_termine', models.BooleanField(default=False)),
                ('fichier_livrable', models.FileField(blank=True, null=True, upload_to='livrables/')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions_status', to='base_de_donnee.groupe')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='base_de_donnee.instruction')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='base_de_donnee.etudiant')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='base_de_donnee.groupe')),
                ('groupeArchive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='base_de_donnee.groupearchive')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='base_de_donnee.etudiant')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='base_de_donnee.groupe')),
                ('groupeArchive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_archive', to='base_de_donnee.groupearchive')),
            ],
        ),
        migrations.CreateModel(
            name='PENotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('etudiants', models.ManyToManyField(blank=True, related_name='pnotifications', to='base_de_donnee.etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='base_de_donnee.professeur'),
        ),
        migrations.CreateModel(
            name='ProfNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnotifications', to='base_de_donnee.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nom_project', models.CharField(max_length=255)),
                ('code_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='base_de_donnee.classe')),
            ],
        ),
        migrations.CreateModel(
            name='P_ressources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='base_de_donnee.project')),
            ],
        ),
        migrations.AddField(
            model_name='instruction',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='base_de_donnee.project'),
        ),
        migrations.AddField(
            model_name='groupearchive',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_de_donnee.project'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_de_donnee.project'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='projets',
            field=models.ManyToManyField(blank=True, related_name='etudiants', to='base_de_donnee.project'),
        ),
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='base_de_donnee.project')),
            ],
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('GroupeArchive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.groupearchive')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.groupe')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.etudiant')),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.sujet')),
            ],
        ),
        migrations.CreateModel(
            name='Taches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_tache', models.TextField()),
                ('status', models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé')], default='En cours', max_length=25)),
                ('deadline', models.DateField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='base_de_donnee.etudiant')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='base_de_donnee.groupe')),
                ('groupeArchive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches_archive', to='base_de_donnee.groupearchive')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
            },
        ),
        migrations.CreateModel(
            name='TempsUtilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('date_start_counter', models.DateTimeField(blank=True, null=True)),
                ('temps_passe', models.DurationField(default=datetime.timedelta(0))),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_temps', to='base_de_donnee.etudiant')),
            ],
            options={
                'verbose_name': "Historique du Temps d'Utilisation",
                'verbose_name_plural': "Historiques du Temps d'Utilisation",
                'ordering': ['-date'],
            },
        ),
    ]
