# Generated by Django 5.1.5 on 2025-01-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
