# Generated by Django 5.1.5 on 2025-02-13 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='etudiants_nbr',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='projets_nbr',
        ),
    ]
