# Generated by Django 5.1.5 on 2025-04-23 07:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='base_de_donnee.project')),
            ],
        ),
    ]
