# Generated by Django 5.1.5 on 2025-06-08 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pevent',
            name='professeur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.professeur'),
        ),
    ]
