# Generated by Django 5.1.5 on 2025-02-25 11:32

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiquetachesetu',
            options={'ordering': ['-date'], 'verbose_name': 'Historique des Tâches', 'verbose_name_plural': 'Historiques des Tâches'},
        ),
        migrations.CreateModel(
            name='TempsUtilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('temps_passe', models.DurationField(default=datetime.timedelta(0))),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_temps', to='base_de_donnee.etudiant')),
            ],
            options={
                'verbose_name': "Historique du Temps d'Utilisation",
                'verbose_name_plural': "Historiques du Temps d'Utilisation",
                'ordering': ['-date'],
            },
        ),
    ]
