# Generated by Django 5.1.5 on 2025-03-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='departement',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='departement',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='specialite',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
