# Generated by Django 5.1.5 on 2025-02-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0002_remove_classe_etudiants_nbr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='description',
            field=models.CharField(default='nouveau classe'),
        ),
    ]
