# Generated by Django 5.1.5 on 2025-02-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0002_alter_historiquetachesetu_options_tempsutilisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempsutilisation',
            name='date_start_counter',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
