# Generated by Django 5.1.5 on 2025-03-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0002_alter_etudiant_departement_alter_etudiant_filiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='email_etudiant',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
