# Generated by Django 5.1.5 on 2025-04-23 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0002_announce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('livrable_requis', models.BooleanField(default=False)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='base_de_donnee.project')),
            ],
        ),
        migrations.CreateModel(
            name='InstructionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_termine', models.BooleanField(default=False)),
                ('fichier_livrable', models.FileField(blank=True, null=True, upload_to='livrables/')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions_status', to='base_de_donnee.groupe')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='base_de_donnee.instruction')),
            ],
        ),
        migrations.CreateModel(
            name='P_ressources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='base_de_donnee.project')),
            ],
        ),
    ]
