# Generated by Django 5.1.5 on 2025-02-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0002_alter_event_end_date_alter_event_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='photo_profil',
            field=models.ImageField(default='static/img/profile.jpeg', upload_to='images/'),
        ),
    ]
