# Generated by Django 5.1.5 on 2025-02-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professeur',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='etudiants', to='base_de_donnee.classe'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='groupes',
            field=models.ManyToManyField(blank=True, related_name='membres', to='base_de_donnee.groupe'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='projets',
            field=models.ManyToManyField(blank=True, related_name='etudiants', to='base_de_donnee.project'),
        ),
    ]
