# Generated by Django 5.1.5 on 2025-02-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0003_alter_etudiant_photo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, related_name='etudiants', to='base_de_donnee.classe'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='groupes',
            field=models.ManyToManyField(blank=True, null=True, related_name='membres', to='base_de_donnee.groupe'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='projets',
            field=models.ManyToManyField(blank=True, null=True, related_name='etudiants', to='base_de_donnee.project'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='photo_profil',
            field=models.ImageField(default='static/img/profile.jpeg', upload_to='images/'),
        ),
    ]
