# Generated by Django 5.1.5 on 2025-03-09 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0003_tempsutilisation_date_start_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_groupe', models.CharField(max_length=255)),
                ('nbr_membre', models.PositiveIntegerField()),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_de_donnee.project')),
            ],
        ),
    ]
