# Generated by Django 5.1.5 on 2025-04-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0003_alter_etudiant_email_etudiant_alter_professeur_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
