# Generated by Django 5.1.5 on 2025-02-22 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0003_etudiant_is_verified_professeur_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='etudiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='base_de_donnee.etudiant'),
        ),
    ]
