# Generated by Django 5.1.5 on 2025-03-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0004_groupearchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='groupesArchive',
            field=models.ManyToManyField(blank=True, related_name='membres', to='base_de_donnee.groupearchive'),
        ),
    ]
