# Generated by Django 5.1.5 on 2025-04-19 13:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0004_classe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('destination_type', models.CharField(choices=[('class', 'Classe'), ('group', 'Groupe'), ('student', 'Étudiant')], max_length=10)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.classe')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.groupe')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.etudiant')),
            ],
        ),
    ]
