# Generated by Django 5.1.5 on 2025-02-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0004_alter_etudiant_classes_alter_etudiant_groupes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taches',
            name='status',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé')], default='En cours', max_length=25),
        ),
    ]
