# Generated by Django 5.1.5 on 2025-02-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0005_instruction_instructionstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='description',
        ),
    ]
