# Generated by Django 5.1.5 on 2025-03-11 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0005_etudiant_groupesarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='groupeArchive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_archive', to='base_de_donnee.groupearchive'),
        ),
        migrations.AddField(
            model_name='notification',
            name='groupeArchive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_archive', to='base_de_donnee.groupearchive'),
        ),
        migrations.AddField(
            model_name='taches',
            name='groupeArchive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches_archive', to='base_de_donnee.groupearchive'),
        ),
    ]
