# Generated by Django 5.1.5 on 2025-02-06 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0005_alter_taches_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='photo_profil',
            field=models.ImageField(default='images/profile.jpeg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='photo_profil',
            field=models.ImageField(default='images/profile.jpeg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_debut',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
