# Generated by Django 5.1.5 on 2025-05-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0006_remove_pnotification_classe_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PNotification',
            new_name='PENotification',
        ),
    ]
