# Generated by Django 5.1.5 on 2025-03-11 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0006_document_groupearchive_notification_groupearchive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='base_de_donnee.groupe'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='base_de_donnee.groupe'),
        ),
        migrations.AlterField(
            model_name='taches',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='base_de_donnee.groupe'),
        ),
    ]
