# Generated by Django 5.1.5 on 2025-05-03 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0006_pevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pevent',
            old_name='date',
            new_name='end',
        ),
        migrations.AddField(
            model_name='pevent',
            name='color',
            field=models.CharField(default='#3788d8', max_length=20),
        ),
        migrations.AddField(
            model_name='pevent',
            name='start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
