# Generated by Django 5.1.5 on 2025-05-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0007_rename_date_pevent_end_pevent_color_pevent_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pevent',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
