# Generated by Django 5.1.5 on 2025-04-02 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0007_alter_document_groupe_alter_notification_groupe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.groupe')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.etudiant')),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.sujet')),
            ],
        ),
    ]
