# Generated by Django 5.1.5 on 2025-05-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0008_alter_pevent_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnotification',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='pnotification',
            name='destination_type',
        ),
        migrations.RemoveField(
            model_name='pnotification',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='pnotification',
            name='student',
        ),
        migrations.AddField(
            model_name='pnotification',
            name='etudiants',
            field=models.ManyToManyField(blank=True, related_name='pnotifications', to='base_de_donnee.etudiant'),
        ),
    ]
