# Generated by Django 5.1.5 on 2025-05-16 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0010_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PENotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('etudiants', models.ManyToManyField(blank=True, related_name='prof_etud_notifications', to='base_de_donnee.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='ProfNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('cerated_at', models.DateTimeField(auto_now_add=True)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnotifications', to='base_de_donnee.professeur')),
            ],
        ),
        migrations.DeleteModel(
            name='PNotification',
        ),
    ]
