# Generated by Django 5.1.5 on 2025-05-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0011_penotification_profnotification_delete_pnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profnotification',
            old_name='cerated_at',
            new_name='created_at',
        ),
    ]
