# Generated by Django 5.1.5 on 2025-05-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0012_rename_cerated_at_profnotification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
